name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore Portal.sln 

    - name: Build
      run: dotnet build Portal.sln --no-restore
          
#    - name: Test
#      run: dotnet test Portal.sln --no-build --verbosity normal

    - name: Restore dependencies
      run: dotnet restore Client.sln 

    - name: Build
      run: dotnet build Client.sln --no-restore
      
#    - name: Test
#      run: dotnet test Client.sln --no-build --verbosity normal
      
